# Data Profiling

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("../data/processed/online_retail_II_processed.csv")

In [3]:
df.shape

(1067371, 8)

In [4]:
df.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')

In [8]:
df.columns.tolist()

['Invoice',
 'StockCode',
 'Description',
 'Quantity',
 'InvoiceDate',
 'Price',
 'Customer ID',
 'Country']

In [10]:
df.dtypes

Invoice            str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
Price          float64
Customer ID    float64
Country            str
dtype: object

In [12]:
df.isna().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(34335)

In [15]:
df.nunique()

Invoice        53628
StockCode       5305
Description     5698
Quantity        1057
InvoiceDate    47635
Price           2807
Customer ID     5942
Country           43
dtype: int64

In [19]:
df["InvoiceDate"].min()

'2009-12-01 07:45:00'

In [20]:
df["InvoiceDate"].max()

'2011-12-09 12:50:00'

In [21]:
(df["Quantity"]<0).sum()

np.int64(22950)

In [38]:
((df["Quantity"]<0) & (df["Invoice"].str.startswith("C"))).sum()

np.int64(19493)

In [37]:
((df["Quantity"]>0) & (df["Invoice"].str.startswith("C"))).sum()

np.int64(1)

In [35]:
((df["Quantity"]>0) & ~(df["Invoice"].str.startswith("C"))).sum()

np.int64(1044420)

In [36]:
((df["Quantity"]<0) & ~(df["Invoice"].str.startswith("C"))).sum()

np.int64(3457)

In [63]:
(df["Price"]==0).sum()

np.int64(6202)

In [62]:
df.loc[df["Price"] == 0, "StockCode"].unique()

<ArrowStringArray>
[ '21733',  '71477', '85123A',  '21646',  '20683',  '21350',  '35956',
 '35605A',  '84292',  '18010',
 ...
  '22217',  '23404',  '85104',  '21693',  '21688', '72801C',  '23395',
  '22578',  '22576',  '23090']
Length: 2971, dtype: str

In [52]:
df["Invoice"].str.startswith("C").sum()

np.int64(19494)

In [59]:
df.loc[
    ~df["StockCode"].str.contains(r"^\D+$", na=False),
    "StockCode"
].unique()

<ArrowStringArray>
[ '85048', '79323P', '79323W',  '22041',  '21232',  '22064',  '21871',
  '21523',  '22350',  '22349',
 ...
  '23578',  '23580',  '23575',  '23560',  '23576',  '23562',  '23561',
  '23609',  '23617',  '23843']
Length: 5288, dtype: str

In [94]:
df[df["StockCode"].str.startswith("TEST")].nunique()

Invoice        17
StockCode       2
Description     1
Quantity        5
InvoiceDate    17
Price           3
Customer ID     5
Country         1
dtype: int64

In [129]:
df.loc[
    (df["Quantity"] < 0) & ~(df["Invoice"].str.startswith("C")),
    "StockCode"
].value_counts().head(30)

StockCode
22423     12
46000M     6
82494L     6
22719      6
46000S     5
84016      5
85017A     5
47566B     5
20852      5
85175      5
21830      5
71477      4
21768      4
84559D     4
84990      4
22028      4
35972      4
21040      4
79000      4
20713      4
21843      4
37476      4
84406B     4
85126      4
21763      4
37464      4
21161      4
22162      4
22034      4
20966      4
Name: count, dtype: int64

In [135]:
df[(df["StockCode"].str.startswith("46000S")) & ~(df["Invoice"].str.startswith("C")) & (df["Quantity"]<0)]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
108086,499767,46000S,NaN,-20,2010-03-02 13:19:00,0.0,NaN,United Kingdom
525234,538161,46000S,Dotcom sales,-100,2010-12-09 17:25:00,0.0,NaN,United Kingdom
547758,538161,46000S,Dotcom sales,-100,2010-12-09 17:25:00,0.0,NaN,United Kingdom
590538,541687,46000S,Dotcom,-300,2011-01-20 15:42:00,0.0,NaN,United Kingdom
957260,573752,46000S,dotcom sales,-90,2011-11-01 09:34:00,0.0,NaN,United Kingdom

In [138]:
df[(df["Invoice"].str.startswith("C")) & (df["Quantity"]>0)]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
76799,C496350,M,Manual,1,2010-02-01 08:24:00,373.57,NaN,United Kingdom

In [142]:
df[df["StockCode"].str.startswith("DCGSLGIRL")]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
101693,499042,DCGSLGIRL,NaN,-57,2010-02-24 13:31:00,0.0,NaN,United Kingdom

In [4]:
df[df["StockCode"].str.startswith("ADJUST")].nunique()

Invoice        70
StockCode       2
Description     4
Quantity        2
InvoiceDate    47
Price          62
Customer ID    53
Country        11
dtype: int64

In [6]:
df[df.duplicated(keep=False)]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
...,...,...,...,...,...,...,...,...
1067136,581538,22068,BLACK PIRATE TREASURE CHEST,1,2011-12-09 11:34:00,0.39,14446.0,United Kingdom
1067150,581538,23318,BOX OF 6 MINI VINTAGE CRACKERS,1,2011-12-09 11:34:00,2.49,14446.0,United Kingdom
1067153,581538,22992,REVOLVER WOODEN RULER,1,2011-12-09 11:34:00,1.95,14446.0,United Kingdom
1067160,581538,22694,WICKER STAR,1,2011-12-09 11:34:00,2.10,14446.0,United Kingdom
1067162,581538,23343,JUMBO BAG VINTAGE CHRISTMAS,1,2011-12-09 11:34:00,2.08,14446.0,United Kingdom

In [7]:
df.duplicated().sum()

np.int64(34335)

In [8]:
df[df.duplicated(keep=False)].groupby(list(df.columns)).size()

Invoice  StockCode  Description                          Quantity  InvoiceDate          Price  Customer ID  Country
489517   21491      SET OF THREE VINTAGE GIFT WRAPS       1        2009-12-01 11:34:00  1.95   16329.0      United Kingdom    2
         21821      GLITTER STAR GARLAND WITH BELLS       1        2009-12-01 11:34:00  3.75   16329.0      United Kingdom    2
         21912      VINTAGE SNAKES & LADDERS              1        2009-12-01 11:34:00  3.75   16329.0      United Kingdom    3
         21913      VINTAGE SEASIDE JIGSAW PUZZLES        1        2009-12-01 11:34:00  3.75   16329.0      United Kingdom    2
         22130      PARTY CONE CHRISTMAS DECORATION       6        2009-12-01 11:34:00  0.85   16329.0      United Kingdom    2
                                                                                                                             ..
C572226  85066      CREAM SWEETHEART MINI CHEST          -1        2011-10-21 13:58:00  12.75  15321.0      United Kingdom    2
C574095  22326      ROUND SNACK BOXES SET OF4 WOODLAND   -1        2011-11-03 09:54:00  2.95   12674.0      France            2
C574510  22360      GLASS JAR ENGLISH CONFECTIONERY      -1        2011-11-04 13:25:00  2.95   15110.0      United Kingdom    2
C575940  23309      SET OF 60 I LOVE LONDON CAKE CASES   -24       2011-11-13 11:38:00  0.55   17838.0      United Kingdom    2
C580764  22667      RECIPE BOX RETROSPOT                 -12       2011-12-06 10:38:00  2.95   14562.0      United Kingdom    2
Length: 25061, dtype: int64

In [12]:
df[df.duplicated(keep=False)].value_counts()

Invoice  StockCode  Description                          Quantity  InvoiceDate          Price  Customer ID  Country
555524   22698      PINK REGENCY TEACUP AND SAUCER       1         2011-06-05 11:37:00  2.95   16923.0      United Kingdom    20
         22697      GREEN REGENCY TEACUP AND SAUCER      1         2011-06-05 11:37:00  2.95   16923.0      United Kingdom    12
537224   70007      HI TEC ALPINE HAND WARMER            1         2010-12-05 16:24:00  1.65   13174.0      United Kingdom    10
572861   22775      PURPLE DRAWERKNOB ACRYLIC EDWARDIAN  12        2011-10-26 12:46:00  1.25   14102.0      United Kingdom     8
496431   84826      ASSTD DESIGN 3D PAPER STICKERS       1         2010-02-01 12:30:00  0.85   16415.0      United Kingdom     6
                                                                                                                              ..
581538   22992      REVOLVER WOODEN RULER                1         2011-12-09 11:34:00  1.95   14446.0      United Kingdom     2
         22694      WICKER STAR                          1         2011-12-09 11:34:00  2.10   14446.0      United Kingdom     2
         23275      SET OF 3 HANGING OWLS OLLIE BEAK     1         2011-12-09 11:34:00  1.25   14446.0      United Kingdom     2
         23318      BOX OF 6 MINI VINTAGE CRACKERS       1         2011-12-09 11:34:00  2.49   14446.0      United Kingdom     2
         23343      JUMBO BAG VINTAGE CHRISTMAS          1         2011-12-09 11:34:00  2.08   14446.0      United Kingdom     2
Name: count, Length: 25061, dtype: int64

In [15]:
df.groupby(list(df.columns)).size().loc[lambda x: x > 1].sort_values(ascending=False).head(20)

Invoice  StockCode  Description                          Quantity  InvoiceDate          Price  Customer ID  Country
555524   22698      PINK REGENCY TEACUP AND SAUCER       1         2011-06-05 11:37:00  2.95   16923.0      United Kingdom    20
         22697      GREEN REGENCY TEACUP AND SAUCER      1         2011-06-05 11:37:00  2.95   16923.0      United Kingdom    12
537224   70007      HI TEC ALPINE HAND WARMER            1         2010-12-05 16:24:00  1.65   13174.0      United Kingdom    10
572861   22775      PURPLE DRAWERKNOB ACRYLIC EDWARDIAN  12        2011-10-26 12:46:00  1.25   14102.0      United Kingdom     8
578289   23395      BELLE JARDINIERE CUSHION COVER       1         2011-11-23 14:07:00  3.75   17841.0      United Kingdom     6
536749   22174      PHOTO CUBE                           2         2010-12-02 13:49:00  1.65   17976.0      United Kingdom     6
502660   17021      NAMASTE SWAGAT INCENSE               6         2010-03-25 17:18:00  0.30   13187.0      United Kingdom     6
537224   22086      PAPER CHAIN KIT 50'S CHRISTMAS       1         2010-12-05 16:24:00  2.95   13174.0      United Kingdom     6
537042   21579      LOLITA  DESIGN  COTTON TOTE BAG      1         2010-12-05 10:45:00  2.25   13838.0      United Kingdom     6
572344   M          Manual                               48        2011-10-24 10:43:00  1.50   14607.0      United Kingdom     6
534219   35953      FOLKART STAR CHRISTMAS DECORATIONS   1         2010-11-21 16:13:00  1.25   13230.0      United Kingdom     6
537208   90082B     DIAMANTE BOW BROOCH RED COLOUR       1         2010-12-05 15:12:00  6.35   15889.0      United Kingdom     6
537265   79000      MOROCCAN TEA GLASS                   12        2010-12-06 11:26:00  0.85   15919.0      United Kingdom     6
537144   21882      SKULLS TAPE                          1         2010-12-05 13:00:00  0.65   15880.0      United Kingdom     6
537051   22730      ALARM CLOCK BAKELIKE IVORY           1         2010-12-05 11:12:00  3.75   15708.0      United Kingdom     6
537265   21163      DO NOT TOUCH MY STUFF DOOR HANGER    1         2010-12-06 11:26:00  1.45   15919.0      United Kingdom     6
496431   84826      ASSTD DESIGN 3D PAPER STICKERS       1         2010-02-01 12:30:00  0.85   16415.0      United Kingdom     6
536464   22866      HAND WARMER SCOTTY DOG DESIGN        1         2010-12-01 12:23:00  2.10   17968.0      United Kingdom     6
525065   20894      HANGING BAUBLE T-LIGHT HOLDER LARGE  1         2010-10-03 14:28:00  2.95   16799.0      United Kingdom     6
537646   21484      CHICK GREY HOT WATER BOTTLE          1         2010-12-07 15:39:00  3.45   17591.0      United Kingdom     6
dtype: int64

In [16]:
df[df.duplicated(keep=False)]["Invoice"].value_counts().head(20)

Invoice
537434    1350
538071    1304
537638    1202
537237    1194
536876    1186
536592    1184
537823    1182
537240    1136
537666    1072
536544    1054
537224     338
537781     322
537640     298
536982     290
536865     280
537643     246
537642     244
536796     242
538153     242
537126     236
Name: count, dtype: int64